name: Deploy

on:
  push:
    branches:
      - next-revamp

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_DATABASE_ID: ${{ secrets.NEXT_PUBLIC_DATABASE_ID }}
      NEXT_PUBLIC_TOKEN: ${{ secrets.NEXT_PUBLIC_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node 14.x
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Build project
        run: yarn install && yarn build
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST_IP }} >> ~/.ssh/known_hosts
      - name: Deploy with rsync
        run: rsync -avz ./out/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/web/