name: Deploy

on:
  schedule:
    - cron: '0 7,12,18 * * 0'
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      placeholder:
        description: 'What do you want?'
        required: false
        default: 'Cookies!!!'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_DATABASE_ID: ${{ secrets.NEXT_PUBLIC_DATABASE_ID }}
      NEXT_PUBLIC_TOKEN: ${{ secrets.NEXT_PUBLIC_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Build project
        run: bun install -y && bun run build
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Deploy with rsync
        run: rsync -avz ./out/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/web/
